on:
  push:
    branches:
    - '**'
    tags-ignore:
    - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
name: build
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        node: [8, 10, 12]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: checkout
      uses: actions/checkout@v1
    - name: cache deps
      uses: actions/cache@v1
      with:
        path: ~/node_modules
        key: ${{ matrix.platform }}-${{ matrix.node }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.platform }}-${{ matrix.node }}-node-
    - name: install deps
      run: npm ci
    - name: run lint
      run: npm run lint
    - name: run tests
      run: npm run test
